# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: newdoin-login
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               serviceName: newdoin-login
#               servicePort: http