# 공식 Nginx 런타임을 부모 이미지로 사용
FROM nginx:alpine

# 웹 페이지를 컨테이너로 복사합니다.
COPY index.html /usr/share/nginx/html


{
  "appId": "92a02ba8-4ed2-4e78-81fc-df75c206167f",
  "displayName": "azure-cli-2024-02-11-09-25-01",
  "password": "cGf8Q~Ou1NvOgYu.AkkFvfXsjOGH1EnC.sIiGdvm",
  "tenant": "4bb7cc33-45f0-47ea-8e0f-0ebdb7587b86"
}


/subscriptions/3c5caecc-2afa-4844-be3b-d56da72d2741/resourceGroups/myResourceGroup/providers/Microsoft.ContainerRegistry/registries/newdoinacr


kubectl -n argocd create secret docker-registry newdoinacr-secret --docker-server=newdoinacr.azurecr.io --docker-username=azure-cli-2024-02-11-09-25-01 --docker-password=cGf8Q~Ou1NvOgYu.AkkFvfXsjOGH1EnC.sIiGdvm -o yaml --dry-run=client | kubectl -n argocd apply -f -